version: "3"
services:
  postgres:
    container_name: postgres2
    image: postgres:latest
    ports:
    - "5433:5432"
    volumes:
    - /Users/piusonobhayedo/data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
 # cockroachdb:
 #   container_name: cockroachdb
 #   image: cockroachdb
 #   ports:
 #   - "26257:26257"
 #   volumes: 
 #   - /Users/piusonobhayedo/data/cockroachdb:/data/cockroachdb
 # pgadmin:
 #   links:
 #   - postgres:postgres2
 #   container_name: pgadmin
 #   image: dpage/pgadmin4
 #   ports:
 #   - "8080:80"
 #   volumes:
  #    - /Users/piusonobhayedo/data/pgadmin:/root/.pgadmin
 #   env_file:
   # - docker.env
  #  networks:
  #  - postgres

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: es01
    environment:
# Using single node for now. Hence I added the line below and commented out the cluster related ones.
      - discovery.type=single-node
#      - node.name=es01
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es02,es03
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=admin
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300 # this is here for single node
#    networks:
#      - elastic

#  es02:
#    image:  docker.elastic.co/elasticsearch/elasticsearch:7.10.0
#    container_name: es02
#    environment:
#      - node.name=es02
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es01,es03
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ELASTIC_PASSWORD=admin
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data02:/usr/share/elasticsearch/data
#    networks:
#      - elastic
#  es03:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
#    container_name: es03
#    environment:
#      - node.name=es03
#      - cluster.name=es-docker-cluster
#      - discovery.seed_hosts=es01,es02
#      - cluster.initial_master_nodes=es01,es02,es03
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - ELASTIC_PASSWORD=admin
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - data03:/usr/share/elasticsearch/data
#    networks:
#      - elastic

#volumes:
#  data01:
#    driver: local
#  data02:
#    driver: local
#  data03:
#    driver: local

networks:
  postgres:
    driver: bridge
#  elastic:
#    driver: bridge